---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# graphicsPLr

<!-- badges: start -->
<!-- badges: end -->

The goal of graphicsPLr is to help with drawing figures in R. Currently it provides a tool for assigning colours or shapes to categories. To be developed

## Installation

You can install the development version of graphicsPLr like so:

``` r
if (!require("devtools")) install.packages("devtools")
devtools::install_github('Phuong-Le/graphicsPLr')
```

## Example


```{r example}
library(graphicsPLr)
## give it the categories 
categories = c('cat', 'dog', 'duck','elephant', 'mouse')
# can't decide on the colours? get_cols() does it for you
get_cols(categories)
# or define your own colours. If the number of categories is greater than the number of specified colours, it will loop over colours the get the right lengths 
get_cols(categories, col_options = c('red','blue'))

## similarly for shapes 
get_shapes(categories)
get_shapes(categories, shape_options = c(16,6,15))
```

